import assert from "node:assert/strict";
import { describe, it } from "node:test";
import {
  ATTRIBUTION_DISCLOSURE,
  PROOF_METRICS,
  PROOF_METRIC_BY_KEY,
  compareMetric,
  formatMetricValue,
  periodVerdict,
} from "./proof";

/**
 * The rule these tests protect: this module can say that something changed
 * while Threadline was engaged. It must never say that Threadline caused it.
 */

const CAUSAL_WORDS = /\b(caused|because of threadline|thanks to|drove|delivered|generated by us|resulted in)\b/i;

describe("metric definitions", () => {
  it("defines a direction and a definition for every metric", () => {
    for (const metric of PROOF_METRICS) {
      assert.ok(metric.definition.length > 20, `${metric.key} needs a real definition`);
      assert.ok(["lower_is_better", "higher_is_better"].includes(metric.direction));
      assert.ok(["client_reported", "platform_observed"].includes(metric.origin));
    }
  });

  it("caveats every commercial metric", () => {
    assert.ok(PROOF_METRIC_BY_KEY.attributableValue.caveat);
    assert.match(PROOF_METRIC_BY_KEY.attributableValue.caveat as string, /not proof of cause/i);
    assert.ok(PROOF_METRIC_BY_KEY.qualifiedInquiries.caveat);
  });

  it("treats founder hours as something only the founder can report", () => {
    assert.equal(PROOF_METRIC_BY_KEY.founderHours.origin, "client_reported");
    assert.equal(PROOF_METRIC_BY_KEY.founderHours.direction, "lower_is_better");
  });

  it("discloses the limits of attribution in fixed wording", () => {
    assert.match(ATTRIBUTION_DISCLOSURE, /not a claim of cause/i);
    assert.match(ATTRIBUTION_DISCLOSURE, /where a buyer named/i);
    assert.doesNotMatch(ATTRIBUTION_DISCLOSURE, CAUSAL_WORDS);
  });
});

describe("comparison", () => {
  const hours = PROOF_METRIC_BY_KEY.founderHours;
  const inquiries = PROOF_METRIC_BY_KEY.qualifiedInquiries;

  it("treats a fall in founder hours as favourable", () => {
    const result = compareMetric(
      hours,
      { value: 10, observed: false },
      { value: 4, observed: false },
    );
    assert.equal(result.delta, -6);
    assert.equal(result.favourable, true);
    assert.equal(result.deltaPct, -60);
  });

  it("treats a fall in inquiries as unfavourable", () => {
    const result = compareMetric(
      inquiries,
      { value: 8, observed: true },
      { value: 5, observed: true },
    );
    assert.equal(result.favourable, false);
    assert.match(result.statement, /lower/);
  });

  it("REPORTS A BLANK RATHER THAN A ZERO when data is missing", () => {
    const noCurrent = compareMetric(hours, { value: 10, observed: false }, { value: null, observed: false });
    assert.equal(noCurrent.delta, null);
    assert.equal(noCurrent.favourable, null);
    assert.match(noCurrent.statement, /not recorded for this month/i);

    const noBaseline = compareMetric(hours, { value: null, observed: false }, { value: 4, observed: false });
    assert.equal(noBaseline.delta, null);
    assert.match(noBaseline.statement, /no baseline/i);

    const neither = compareMetric(hours, { value: null, observed: false }, { value: null, observed: false });
    assert.match(neither.statement, /not recorded for either period/i);
  });

  it("does not divide by a zero baseline", () => {
    const result = compareMetric(
      inquiries,
      { value: 0, observed: true },
      { value: 4, observed: true },
    );
    assert.equal(result.delta, 4);
    assert.equal(result.deltaPct, null);
    assert.equal(result.favourable, true);
  });

  it("reports no movement as unchanged rather than as a win", () => {
    const result = compareMetric(hours, { value: 5, observed: false }, { value: 5, observed: false });
    assert.equal(result.favourable, null);
    assert.match(result.statement, /unchanged/i);
  });

  it("NEVER CLAIMS CAUSATION in any statement it produces", () => {
    for (const metric of PROOF_METRICS) {
      for (const [baseline, current] of [
        [10, 4],
        [4, 10],
        [0, 3],
        [5, 5],
      ] as const) {
        const result = compareMetric(
          metric,
          { value: baseline, observed: false },
          { value: current, observed: true },
        );
        assert.doesNotMatch(
          result.statement,
          CAUSAL_WORDS,
          `${metric.key} produced a causal claim: ${result.statement}`,
        );
      }
    }
  });

  it("says the period is one Threadline was engaged for, not one it caused", () => {
    const result = compareMetric(hours, { value: 10, observed: false }, { value: 4, observed: false });
    assert.match(result.statement, /over the period threadline has been engaged/i);
  });

  it("says whether the baseline was measured or reported", () => {
    const reported = compareMetric(hours, { value: 10, observed: false }, { value: 4, observed: false });
    assert.match(reported.statement, /reported baseline/i);

    const measured = compareMetric(
      PROOF_METRIC_BY_KEY.contentOutput,
      { value: 4, observed: true },
      { value: 9, observed: true },
    );
    assert.match(measured.statement, /measured baseline/i);
  });
});

describe("period verdict", () => {
  const build = (pairs: [number, number][]) =>
    pairs.map(([baseline, current], i) =>
      compareMetric(
        PROOF_METRICS[i % PROOF_METRICS.length]!,
        { value: baseline, observed: false },
        { value: current, observed: false },
      ),
    );

  it("reports honestly when more went backwards than forwards", () => {
    // founderHours (lower better) rising, contentOutput (higher better) falling.
    const verdict = periodVerdict(build([[4, 9], [10, 3]]));
    assert.equal(verdict.unfavourable, 2);
    assert.equal(verdict.favourable, 0);
    assert.match(verdict.headline, /against the intended direction/i);
    assert.match(verdict.headline, /honest read/i);
  });

  it("reports a good month as a count, not a claim", () => {
    const verdict = periodVerdict(build([[9, 4], [3, 10]]));
    assert.equal(verdict.favourable, 2);
    assert.match(verdict.headline, /moved in the intended direction/i);
    assert.doesNotMatch(verdict.headline, CAUSAL_WORDS);
  });

  it("says so when there is not enough data", () => {
    const verdict = periodVerdict([
      compareMetric(
        PROOF_METRIC_BY_KEY.founderHours,
        { value: null, observed: false },
        { value: null, observed: false },
      ),
    ]);
    assert.equal(verdict.missing, 1);
    assert.match(verdict.headline, /not enough recorded data/i);
  });

  it("never produces a causal headline", () => {
    for (const pairs of [
      [[4, 9]],
      [[9, 4]],
      [[5, 5]],
      [[9, 4], [4, 9]],
    ] as [number, number][][]) {
      assert.doesNotMatch(periodVerdict(build(pairs)).headline, CAUSAL_WORDS);
    }
  });
});

describe("formatting", () => {
  it("renders an em dash for a missing value rather than zero", () => {
    assert.equal(formatMetricValue(null, "count"), "—");
    assert.equal(formatMetricValue(Number.NaN, "hours"), "—");
  });

  it("formats each shape correctly", () => {
    assert.equal(formatMetricValue(4.25, "hours"), "4.3 hrs");
    assert.equal(formatMetricValue(1, "days"), "1 day");
    assert.equal(formatMetricValue(2.5, "days"), "2.5 days");
    assert.equal(formatMetricValue(3.14, "percent"), "3.1%");
    assert.equal(formatMetricValue(1234, "count"), "1,234");
  });

  it("reads money from minor units", () => {
    assert.equal(formatMetricValue(800_000, "money", "GBP"), "£8,000");
  });
});
