/**
 * Demo workspace content — Northbeam Advisory.
 *
 * A fictional high-ticket, founder-led consulting business. Everything here is
 * written to be specific and believable: a prospect on a sales call should be
 * able to read any screen and recognise their own operation.
 *
 * Rules this data follows:
 *   - No lorem ipsum, no placeholder text.
 *   - No fabricated third-party brands presented as real customers.
 *   - Numbers are internally consistent: performance supports the insights the
 *     dashboard derives, and the pipeline supports the attribution shown.
 */

export const COMPANY = {
  name: "Northbeam Advisory",
  slug: "northbeam",
  website: "https://northbeamadvisory.com",
  industry: "B2B consulting — sales operations",
  geography: "United Kingdom, serving UK and EU",
  description:
    "Northbeam Advisory rebuilds the sales operation inside founder-led B2B SaaS companies. We work with a small number of clients at a time, going into the business for twelve weeks to fix how deals are qualified, how the pipeline is measured, and how the founder spends their selling time. We are not a fractional sales hire and we do not run outbound campaigns — we install a system the existing team runs after we leave.",
  teamSize: "4 (founder plus three consultants)",
  revenueRange: "£1.2m annual revenue",
  currency: "GBP",
  timezone: "Europe/London",
};

export const FOUNDER = {
  name: "Alex Morgan",
  email: "alex@northbeamadvisory.com",
  title: "Founder",
  bio: "Alex Morgan spent eleven years building and running sales teams inside B2B SaaS companies before starting Northbeam Advisory. Two of those companies exited; one did not, and Alex is more useful because of the one that did not. Alex now works with founders in the £500k–£5m range who are trying to get out of being the only person who can close a deal.",
  experience:
    "VP Sales at a Series B workflow-automation company (£0.9m to £7.4m ARR over three years). Head of Revenue Operations at a compliance SaaS business through a failed scale-up and a subsequent restructure. Independent consultant since 2021, now operating as Northbeam Advisory with three consultants.",
  beliefs: [
    "Most founder-led sales problems are qualification problems wearing a pipeline costume.",
    "You cannot fix a sales process by hiring someone to run a process that does not exist.",
    "A forecast that is wrong in a predictable direction is more useful than a forecast that is wrong randomly.",
    "The founder should be the last person in the deal, not the first.",
    "If your CRM requires discipline to be accurate, it is designed wrong.",
  ],
  opinions: [
    "Hiring SDRs before the founder can articulate why deals are lost is the single most expensive mistake in early-stage B2B.",
    "Most 'we need more pipeline' conversations are actually 'we close too few of the deals we already have'.",
    "Discovery calls that end with a demo booked are usually bad discovery calls.",
    "Sales enablement content is mostly a substitute for a decision nobody wants to make about positioning.",
    "Commission plans with more than two variables are a tax on your own attention.",
  ],
  stories: [
    "The quarter I forecast £480k and closed £120k, and what I found when I went back through the call recordings.",
    "The client who fired two SDRs on my recommendation and grew 40% the following year with the same two AEs.",
    "The first company I worked at that died — and the eighteen months of pipeline reports that said everything was fine.",
    "The founder who insisted the problem was lead volume, until we counted how many qualified deals had gone dark in the last ninety days.",
    "Losing a deal I had forecast at 90% because nobody had ever spoken to the person who signs.",
  ],
  credentials: [
    "Eleven years operating B2B SaaS sales teams",
    "Two exits, one restructure",
    "Twenty-seven companies advised since 2021",
    "Regular guest on operator-focused B2B podcasts",
  ],
};

export const VOICE = {
  tone: "Direct, unsentimental, occasionally dry. Alex speaks like an operator who has seen the failure mode before and is not going to be dramatic about it. Never motivational. Never uses urgency as a device. Willing to say 'I got this wrong' as a first-person opener, because it is the fastest way to earn the right to be blunt afterwards.",
  vocabulary:
    "Operator language: pipeline, qualification, forecast, cycle time, win rate, discovery, close. Avoids MBA abstraction ('synergies', 'alignment', 'best practice') and avoids startup slang ('crushing it', '10x', 'growth hacking'). Uses specific numbers where they exist and says 'I do not have a number for that' where they do not.",
  sentenceStructure:
    "Short declarative sentences. One idea per line. Frequently opens with a flat statement, then qualifies it in the next line. Uses the two-beat structure: claim, then the uncomfortable detail that makes the claim credible.",
  humour:
    "Dry and infrequent. Understatement rather than jokes. Usually directed at their own past mistakes, never at a client or a prospect.",
  phrasesUsed: [
    "Here is what I actually see.",
    "That is the symptom, not the cause.",
    "I got this wrong for two years.",
    "Let me be specific.",
    "The uncomfortable version of this is…",
    "You already know the answer to this one.",
  ],
  phrasesAvoided: [
    "Game-changing",
    "Crushing it",
    "Let that sink in",
    "Here's the thing…",
    "In today's fast-paced world",
    "Unlock your potential",
    "Secret / hack / trick",
  ],
  soundsLikeMe: [
    "Most founders think they have a lead problem. Almost none of them do. They have a qualification problem, and it shows up two stages later as a pipeline problem.",
    "I forecast £480k one quarter and closed £120k. The forecast was not optimistic. It was uninformed. Those are different failures and they need different fixes.",
    "If your best AE leaves and the forecast collapses, you did not have a process. You had a person.",
  ],
  notMe: [
    "🚀 Ready to 10x your pipeline? Here are 7 game-changing hacks that will TRANSFORM your sales team!",
    "In today's hyper-competitive landscape, sales excellence has never been more critical to organisational success.",
    "Comment 'GROWTH' below and I'll DM you my free 47-page playbook!",
  ],
};

export const OFFER = {
  name: "The Sales Operating System",
  price: 8000,
  priceModel: "one_off",
  mechanism:
    "A twelve-week installation. Weeks 1–3 we audit: call recordings, closed-lost analysis, and the actual definition of a qualified deal as your team applies it, not as it is written down. Weeks 4–8 we rebuild qualification criteria, pipeline stages, and the forecast model, then run them live with your team on real deals. Weeks 9–12 we hand over: the founder steps back from early-stage calls, the team runs the system, and we measure whether the forecast held.",
  outcome:
    "The founder stops being the only person who can qualify and close, and the forecast becomes accurate enough to make hiring and cash decisions against.",
  differentiators: [
    "We work on your live deals during the engagement, not on a document.",
    "We do not run outbound or take a commission — we have no incentive to inflate your pipeline.",
    "Fixed twelve weeks with a defined handover. We leave.",
    "Maximum four clients at a time.",
    "The founder is in every working session. This does not work delegated.",
  ],
  guarantee:
    "If, by week 6, we have not identified a specific structural cause of your forecast variance, we stop the engagement and refund the remaining balance.",
  ctas: [
    "If your forecast has been wrong three quarters running, the diagnostic is the place to start.",
    "Comment 'system' and I will send you the qualification framework we install.",
    "Book a diagnostic call — the link is in my profile.",
  ],
  exclusions:
    "We do not build outbound sequences, hire your reps, write your marketing, or implement your CRM. We define what the CRM must capture; your team or your RevOps partner configures it.",
};

export const ICP = {
  name: "B2B SaaS founders, £500k–£5m ARR",
  description:
    "Founder-led B2B SaaS companies past product-market fit but before a repeatable sales motion. Typically 8–40 staff with one to four people carrying a number. The founder is still personally involved in most closed deals and knows this is the constraint.",
  firmographics:
    "£500k–£5m ARR. B2B software, usually with an annual contract between £8k and £120k. UK or EU headquartered. Venture-backed or profitably bootstrapped — both work. One to four quota-carrying staff, often promoted from customer success or hired without a manager.",
  pains: [
    "The forecast is wrong every quarter and nobody can say why",
    "The founder is in every deal that closes and cannot step out",
    "Reps say the deal is progressing right up until it goes dark",
    "Nobody agrees on what 'qualified' actually means",
    "Hired an SDR or AE who is not producing and nobody knows whether it is the hire or the process",
    "Pipeline looks healthy in the CRM and does not convert",
    "Closed-lost reasons are all recorded as 'price' or 'timing'",
  ],
  desires: [
    "A forecast accurate enough to hire against",
    "Deals that close without the founder in the room",
    "A clear, shared definition of a qualified opportunity",
    "Knowing which deals to walk away from earlier",
    "Getting ten hours a week back from deal firefighting",
    "Confidence that the next sales hire will work",
  ],
  objections: [
    "We have tried a sales consultant before and got a slide deck",
    "Our sales motion is unusual, generic frameworks will not fit",
    "We cannot afford to slow down the team for twelve weeks",
    "£8,000 is a lot when we are not sure the problem is the process",
    "I do not have time to be in every session",
    "We need more leads, not a better process",
    "Our reps will resist another change",
  ],
  triggers: [
    "Third consecutive quarter of forecast miss",
    "A senior rep leaves and pipeline visibility disappears with them",
    "A funding round or board meeting that requires a defensible forecast",
    "First sales hire under-performing after six months",
    "Founder returning from a break to find deals stalled",
    "A large deal lost late in the cycle for a reason nobody saw coming",
  ],
  sophistication: "moderate",
};

export const PROOF = [
  {
    kind: "metric",
    title: "Forecast variance reduced across engagements",
    body: "Average absolute forecast variance across the last nine completed engagements, measured in the quarter following handover versus the quarter before the engagement began.",
    metricLabel: "Average forecast variance",
    metricValue: "From 42% to 14%",
    source: "Northbeam internal engagement records, 2024–2025",
    claimStatus: "allowed",
  },
  {
    kind: "case_study",
    title: "Compliance SaaS, £2.1m ARR — founder removed from early-stage calls",
    body: "The founder was joining 90% of first calls. We rebuilt qualification criteria and ran them live for six weeks with two AEs. By handover the founder joined only deals above £40k that had passed stage two. Founder selling time fell from roughly 14 hours a week to 4.",
    source: "Client engagement, 2025. Named reference available on request.",
    claimStatus: "allowed",
  },
  {
    kind: "case_study",
    title: "Workflow SaaS, £900k ARR — two SDRs removed, growth continued",
    body: "The client had hired two SDRs to solve what they believed was a lead volume problem. Closed-lost analysis showed a 19% stage-two-to-three conversion rate on inbound that was already qualified. We recommended removing the SDR layer and rebuilding qualification. The following year the same two AEs grew the number without the SDR cost.",
    source: "Client engagement, 2024. Reference available on request.",
    claimStatus: "allowed",
  },
  {
    kind: "testimonial",
    title: "\"The first consultant who worked on our actual deals\"",
    body: "Alex spent three weeks in our call recordings before proposing anything. Everyone else we spoke to led with their framework. By week six we knew exactly which deals we should never have forecast.",
    source: "Founder, B2B SaaS, £3m ARR. Full attribution available on request.",
    claimStatus: "allowed",
  },
  {
    kind: "credential",
    title: "Twenty-seven engagements since 2021",
    metricLabel: "Companies advised",
    metricValue: "27",
    source: "Northbeam internal records",
    claimStatus: "allowed",
  },
  {
    kind: "metric",
    title: "Average founder selling hours released",
    body: "Self-reported by clients at handover, comparing hours spent on live deals in the month before the engagement with the month after.",
    metricLabel: "Founder hours per week released",
    metricValue: "Approximately 8",
    source: "Client self-report at handover, n=9",
    claimStatus: "needs_review",
  },
];

export const CONTENT_RULES = {
  platforms: ["linkedin", "youtube_shorts", "youtube"],
  formats: ["short_form", "talking_head", "text_post", "long_form"],
  preferredCtas: [
    "Comment 'system' and I will send you the qualification framework.",
    "If your forecast has been wrong three quarters running, the diagnostic is the place to start.",
    "The booking link is in my profile.",
  ],
  cadencePerWeek: 4,
  pillars: [
    "Founder POV",
    "Qualification mechanics",
    "Forecasting and pipeline",
    "Hiring and team structure",
    "Case studies and proof",
    "Objection handling",
  ],
  topics: [
    "Qualification frameworks",
    "Forecast accuracy",
    "Closed-lost analysis",
    "First sales hire",
    "Founder-led selling",
    "Pipeline hygiene",
  ],
  bannedTopics: [
    "Specific client names without written permission",
    "Commentary on named competitors' clients",
    "Fundraising advice — outside our competence",
    "Anything implying guaranteed revenue outcomes",
  ],
  complianceNotes:
    "Client results may only be referenced in anonymised form unless written permission is on file. Never state or imply a guaranteed revenue outcome. Forecast-variance figures must cite the internal engagement record they come from.",
};

export const COMPETITORS = [
  {
    name: "Meridian Revenue Partners",
    url: "https://example-meridian.com",
    platforms: ["linkedin", "youtube"],
    positioning:
      "Enterprise-focused revenue consultancy. Long engagements, heavy documentation, sells to CROs rather than founders.",
    notes:
      "Publishes twice a week on LinkedIn. Almost entirely framework-led content with no first-person material. Consistently strong reach on posts about forecasting, weak on anything about hiring. Their weakness is that a founder cannot see themselves in the content.",
    threatLevel: "medium",
  },
  {
    name: "Cadence Sales Lab",
    url: "https://example-cadence.com",
    platforms: ["linkedin", "tiktok", "instagram"],
    positioning:
      "High-volume sales training for SDR teams. Low price point, subscription model, targets sales managers not founders.",
    notes:
      "Publishes daily. Very high engagement, very low relevance to our ICP. Useful as a signal of which topics get attention, not as a competitor for the same buyer.",
    threatLevel: "low",
  },
  {
    name: "Harlow & Finch",
    url: "https://example-harlow.com",
    platforms: ["linkedin"],
    positioning:
      "Fractional CRO placements. Sells a person, not a system. Directly competes for the same budget line.",
    notes:
      "The real competitor. When a founder is deciding between us and them, the decision is 'buy a system' versus 'buy a person'. Their content leans on the credibility of individual operators. Our counter-position is that a person leaves and a system does not.",
    threatLevel: "high",
  },
  {
    name: "Ridgeline Growth",
    url: "https://example-ridgeline.com",
    platforms: ["linkedin", "youtube"],
    positioning:
      "Outbound agency expanding into advisory. Positions pipeline volume as the primary constraint.",
    notes:
      "Directly opposed to our thesis, which makes them useful. Their content asserts that more pipeline solves conversion problems. Good source of contrarian hooks.",
    threatLevel: "medium",
  },
  {
    name: "Independent operator accounts",
    platforms: ["linkedin", "x"],
    positioning:
      "Individual ex-VP Sales operators publishing personal commentary. No agency, no offer, high credibility.",
    notes:
      "Not competing for budget, but competing for the same attention in the feed. Their strongest material is always first-person and specific. This is the format we are closest to and should be beating.",
    threatLevel: "medium",
  },
];

export const RESEARCH: {
  kind: string;
  title: string;
  body?: string;
  competitor?: string;
  platform?: string;
  sourceName?: string;
  tags: string[];
  metrics?: { views?: number; likes?: number; comments?: number };
}[] = [
  {
    kind: "objection",
    title: "\"We've tried a sales consultant before and got a slide deck\"",
    body: "Raised on four of the last nine diagnostic calls, usually within the first ten minutes. The underlying fear is paying for analysis rather than change. Best counter so far has been describing the week-4 live-deal sessions specifically.",
    sourceName: "Diagnostic call notes",
    tags: ["objection", "pain"],
  },
  {
    kind: "objection",
    title: "\"We need more leads, not a better process\"",
    body: "The most common objection and the one most worth addressing publicly, because it is the belief that keeps the buyer from recognising their own problem. Countered with closed-lost data, not argument.",
    sourceName: "Diagnostic call notes",
    tags: ["objection", "desire"],
  },
  {
    kind: "objection",
    title: "\"£8,000 is a lot when we're not sure the problem is the process\"",
    body: "Price objection that is really a diagnosis objection. Buyers are not resisting the number, they are resisting committing before they know the cause. The week-6 guarantee exists specifically for this.",
    sourceName: "Diagnostic call notes",
    tags: ["objection", "offer"],
  },
  {
    kind: "objection",
    title: "\"I don't have time to be in every session\"",
    body: "Comes up with founders who are the constraint and know it. The honest answer is that the engagement does not work without them, and saying so has qualified out two poor-fit clients.",
    sourceName: "Diagnostic call notes",
    tags: ["objection"],
  },
  {
    kind: "customer_language",
    title: "\"Our pipeline looks fine right up until it doesn't\"",
    body: "Almost verbatim from three separate founders. This phrasing describes the experience of late-stage deal collapse without naming the cause. Strong hook material because it is recognition, not education.",
    sourceName: "Diagnostic calls, three separate founders",
    tags: ["customer-language", "pain"],
  },
  {
    kind: "customer_language",
    title: "\"I'm the bottleneck and I know I'm the bottleneck\"",
    body: "Founders arrive already diagnosing themselves. They do not need convincing that they are the constraint — they need a mechanism for stepping out. Content that explains the problem again under-performs; content that shows the mechanism performs.",
    sourceName: "Diagnostic calls",
    tags: ["customer-language", "pain", "desire"],
  },
  {
    kind: "customer_language",
    title: "\"Every closed-lost is marked price or timing\"",
    body: "Said with visible frustration. Founders know the loss reasons are wrong but do not have a way to get better ones. Direct route into the closed-lost analysis topic.",
    sourceName: "Diagnostic calls",
    tags: ["customer-language", "pain"],
  },
  {
    kind: "customer_language",
    title: "\"I don't know if it's the hire or the process\"",
    body: "About an underperforming first sales hire. Sits underneath a genuinely expensive decision — whether to fire someone — which makes this high commercial intent.",
    sourceName: "Diagnostic calls",
    tags: ["customer-language", "pain"],
  },
  {
    kind: "question",
    title: "\"When should we hire our first AE?\"",
    body: "The single most frequent inbound question. Usually asked as a timing question when it is actually a readiness question.",
    sourceName: "Inbound DMs and comments",
    tags: ["question"],
  },
  {
    kind: "question",
    title: "\"What should our sales stages actually be?\"",
    body: "Asked frequently. Almost always a symptom of stages that describe internal activity rather than buyer commitment.",
    sourceName: "Inbound DMs",
    tags: ["question"],
  },
  {
    kind: "question",
    title: "\"How do I know if a deal is real?\"",
    body: "The qualification question in plain language. Worth answering in exactly these words rather than in framework terms.",
    sourceName: "Comments on LinkedIn",
    tags: ["question", "hook"],
  },
  {
    kind: "question",
    title: "\"How long should our sales cycle be?\"",
    body: "Usually asked by founders whose cycle has quietly doubled. The interesting answer is about variance rather than length.",
    sourceName: "Inbound DMs",
    tags: ["question"],
  },
  {
    kind: "competitor_post",
    title: "Meridian: 'The five-stage forecast model' carousel",
    body: "Framework-led carousel, no first-person material. Strong reach for their account. Comments are mostly other consultants rather than founders, which suggests it reaches peers rather than buyers.",
    competitor: "Meridian Revenue Partners",
    platform: "linkedin",
    tags: ["competitor", "format"],
    metrics: { views: 41200, likes: 612, comments: 47 },
  },
  {
    kind: "competitor_post",
    title: "Harlow & Finch: 'Why fractional beats full-time' post",
    body: "Direct positioning against permanent hires. Well argued. Does not address what happens when the fractional operator leaves — which is our opening.",
    competitor: "Harlow & Finch",
    platform: "linkedin",
    tags: ["competitor", "offer", "objection"],
    metrics: { views: 28900, likes: 431, comments: 88 },
  },
  {
    kind: "competitor_post",
    title: "Ridgeline: 'Pipeline is the only metric that matters' video",
    body: "Asserts volume as the primary constraint. Popular, and directly contradicts our thesis. This is the best available contrarian anchor — we can name the belief without naming them.",
    competitor: "Ridgeline Growth",
    platform: "linkedin",
    tags: ["competitor", "hook", "trend"],
    metrics: { views: 67400, likes: 1140, comments: 203 },
  },
  {
    kind: "competitor_post",
    title: "Independent operator: 'The deal I lost at 90%' post",
    body: "First-person failure story with a specific number. Enormous engagement relative to the account size. This is the format closest to Alex's natural voice and the clearest evidence that it works in this market.",
    competitor: "Independent operator accounts",
    platform: "linkedin",
    tags: ["competitor", "hook", "breakout", "format"],
    metrics: { views: 154000, likes: 3820, comments: 412 },
  },
  {
    kind: "competitor_post",
    title: "Cadence: daily SDR tips series",
    body: "High volume, high engagement, wrong audience. Reaches sales reps, not founders. Useful only as evidence that tactical content wins attention while strategic content wins buyers.",
    competitor: "Cadence Sales Lab",
    platform: "linkedin",
    tags: ["competitor", "format"],
    metrics: { views: 22100, likes: 890, comments: 34 },
  },
  {
    kind: "trend",
    title: "Rising discussion of sales team over-hiring corrections",
    body: "Noticeably more founder commentary about having hired too early, and more willingness to say so publicly. The taboo around admitting a bad sales hire is weakening. This opens the SDR-timing topic considerably.",
    sourceName: "LinkedIn feed observation, ongoing",
    tags: ["trend", "hook"],
  },
  {
    kind: "trend",
    title: "Forecast accuracy appearing in board-level conversation",
    body: "Founders increasingly report that investors are asking for forecast methodology, not just the number. Raises the commercial stakes of our core topic.",
    sourceName: "Diagnostic calls and community discussion",
    tags: ["trend", "desire"],
  },
  {
    kind: "trend",
    title: "Scepticism toward framework-led consulting content",
    body: "Growing visible fatigue with acronym frameworks in the comments under competitor posts. Multiple 'this is just MEDDIC with new labels' replies. Suggests the mechanism should be explained without naming it as a framework.",
    sourceName: "Competitor post comments",
    tags: ["trend", "format"],
  },
  {
    kind: "content_example",
    title: "Own post: 'I forecast £480k and closed £120k' — best performer to date",
    body: "First-person failure opener with a specific number, followed by the structural cause. Highest reach and highest inbound of anything published. The structure to repeat: personal number, then mechanism.",
    platform: "linkedin",
    sourceName: "Northbeam LinkedIn",
    tags: ["breakout", "hook", "format", "proof"],
    metrics: { views: 187000, likes: 2940, comments: 218 },
  },
  {
    kind: "content_example",
    title: "Own post: 'Five questions to qualify a deal' — under-performed",
    body: "Listicle format, no first-person anchor, no specific example. Reach roughly a fifth of the median. Useful negative evidence: the same information framed as a list does not travel.",
    platform: "linkedin",
    sourceName: "Northbeam LinkedIn",
    tags: ["format"],
    metrics: { views: 9400, likes: 84, comments: 6 },
  },
  {
    kind: "content_example",
    title: "Own video: 'Why your closed-lost data is useless'",
    body: "Talking head, ninety seconds, opens on a flat contrarian statement. Strong retention through to the mechanism section, then a drop at the CTA. Suggests the CTA is too long.",
    platform: "youtube_shorts",
    sourceName: "Northbeam YouTube",
    tags: ["format", "cta"],
    metrics: { views: 64000, likes: 1210, comments: 96 },
  },
  {
    kind: "offer_example",
    title: "Harlow & Finch pricing page structure",
    body: "Leads with the operator's CV rather than the outcome. Monthly retainer with no defined end. The absence of an end date is worth contrasting against directly — our twelve-week handover is the differentiator.",
    competitor: "Harlow & Finch",
    tags: ["offer", "competitor"],
  },
  {
    kind: "offer_example",
    title: "Meridian engagement structure",
    body: "Six-month minimum, enterprise pricing, phased deliverables that are documents rather than live-deal work. Their length is a liability for our ICP, who cannot commit six months.",
    competitor: "Meridian Revenue Partners",
    tags: ["offer", "competitor"],
  },
  {
    kind: "source",
    title: "Quarterly B2B SaaS benchmark reports",
    body: "Useful for market-level context on cycle length and win rates. Must be cited explicitly if any figure is used in content — no benchmark number goes into a script unattributed.",
    sourceName: "Industry benchmark publications",
    tags: ["proof"],
  },
  {
    kind: "customer_language",
    title: "\"By the time I get involved it's already gone wrong\"",
    body: "Describes the founder being pulled into deals as a rescue mechanism rather than by design. Good hook material because it names a pattern founders recognise immediately.",
    sourceName: "Diagnostic calls",
    tags: ["customer-language", "pain", "hook"],
  },
  {
    kind: "question",
    title: "\"Should the founder still be on sales calls at £3m ARR?\"",
    body: "Asked directly in a community thread and repeatedly in DMs. High-intent question — the person asking is usually within a quarter of making a hiring decision.",
    sourceName: "Founder community thread",
    tags: ["question", "desire"],
  },
];

export const PATTERNS = [
  {
    kind: "learning",
    title: "First-person failure openers outperform framework openers by roughly 3x",
    description:
      "Across published content, pieces opening with a specific first-person mistake and a real number reach roughly three times the median. Pieces opening by naming a framework sit below median. The evidence is consistent across both LinkedIn and short-form video, and matches the strongest competitor post observed.",
    status: "validated",
    confidence: 82,
    impact: 5,
    effort: 2,
    nextExperiment:
      "Open the next four pieces with a first-person number and withhold any framework name until after the second beat.",
    detectedBy: "performance_loop",
  },
  {
    kind: "learning",
    title: "Content naming the qualification-versus-lead-volume belief produces the most inbound",
    description:
      "Pieces that directly address 'we need more leads' as a misdiagnosis account for a disproportionate share of recorded inbound inquiries relative to their reach. Reach is mid-range; commercial signal is the highest of any theme.",
    status: "validated",
    confidence: 71,
    impact: 5,
    effort: 2,
    nextExperiment:
      "Publish two more pieces on this belief within the next fortnight and tag every resulting inquiry to measure whether the rate holds.",
    detectedBy: "performance_loop",
  },
  {
    kind: "pattern",
    title: "Retention drops sharply at the CTA on short-form video",
    description:
      "Across short-form pieces with retention data, the curve holds through the mechanism section and falls at the closing CTA. The CTAs currently in use run two to three sentences.",
    status: "open",
    confidence: 64,
    impact: 3,
    effort: 1,
    nextExperiment:
      "Cut the CTA to a single clause on the next three short-form pieces and compare retention in the final 15%.",
    detectedBy: "performance_loop",
  },
  {
    kind: "pattern",
    title: "Hiring-related content reaches further than forecasting content",
    description:
      "Pieces about sales hiring consistently out-reach pieces about forecast mechanics, despite forecasting being closer to the offer. Hiring is the more emotionally live topic; forecasting is the more commercially relevant one.",
    status: "open",
    confidence: 58,
    impact: 4,
    effort: 2,
    nextExperiment:
      "Test a piece that enters through hiring and exits into forecasting, to see whether reach and intent can be combined.",
    detectedBy: "manual",
  },
  {
    kind: "hypothesis",
    title: "Naming a competitor belief without naming the competitor increases engagement",
    description:
      "The highest-comment competitor post asserts that pipeline volume is the primary constraint. Directly contradicting a widely held belief appears to drive discussion. Untested on our own account.",
    status: "testing",
    confidence: 45,
    impact: 4,
    effort: 1,
    nextExperiment:
      "Publish one piece that states the opposing belief in the hook and defends the counter-position with closed-lost data.",
    detectedBy: "manual",
  },
  {
    kind: "hypothesis",
    title: "Listicle formats under-perform for this audience",
    description:
      "One clear negative data point: the five-questions listicle reached roughly a fifth of median. A single instance is not a pattern, but it is consistent with visible comment fatigue toward framework content.",
    status: "open",
    confidence: 38,
    impact: 3,
    effort: 1,
    nextExperiment:
      "Publish one further list-format piece to confirm or rule out before removing the format from rotation.",
    detectedBy: "performance_loop",
  },
  {
    kind: "outlier",
    title: "One post produced four of the last quarter's qualified conversations",
    description:
      "A single piece on closed-lost analysis is linked to four recorded inquiries, three of which qualified. Reach was unremarkable. This suggests topic-to-intent matters more than reach for pipeline.",
    status: "open",
    confidence: 55,
    impact: 5,
    effort: 2,
    nextExperiment:
      "Republish the same argument in long-form video and track whether the inquiry rate transfers across format.",
    detectedBy: "performance_loop",
  },
  {
    kind: "test",
    title: "Three-part series on the cost of hiring SDRs too early",
    description:
      "Running test. Three connected pieces published over eight days, each entering the topic from a different angle: the hiring decision, the closed-lost data, and the correction. Measuring whether a series outperforms three unconnected pieces on the same theme.",
    status: "testing",
    confidence: 50,
    impact: 4,
    effort: 3,
    nextExperiment:
      "Complete the third piece and compare aggregate reach and inbound against the three preceding standalone pieces.",
    detectedBy: "manual",
  },
];

/**
 * Ideas. Deliberately more than needed, at varied quality and status, so the
 * backlog looks like a real working backlog rather than a curated list.
 */
export const IDEAS = [
  {
    title: "The £480k forecast that closed at £120k",
    concept:
      "The specific quarter Alex got a forecast catastrophically wrong, what the call recordings revealed afterwards, and why the failure was uninformed rather than optimistic.",
    pillar: "Founder POV",
    platform: "linkedin",
    format: "talking_head",
    angle: "First-person failure with a real number, then the structural cause.",
    hookConcept: "I forecast £480k one quarter. We closed £120k.",
    objective: "Authority through admitted failure",
    cta: "Comment 'system' and I will send you the qualification framework.",
    commercialIntent: "high",
    scores: { novelty: 74, relevance: 96, proof: 92, fit: 94 },
    status: "scripted",
    rationale:
      "Matches the validated first-person-opener learning and the strongest competitor format observed. Highest proof strength available because the number is Alex's own.",
  },
  {
    title: "You do not have a lead problem",
    concept:
      "Directly contradicts the most common founder self-diagnosis, using closed-lost data as the argument rather than assertion.",
    pillar: "Qualification mechanics",
    platform: "linkedin",
    format: "talking_head",
    angle: "Name the belief, then dismantle it with the buyer's own numbers.",
    hookConcept: "Most founders think they have a lead problem. Almost none of them do.",
    objective: "Reframe the problem",
    cta: "If your forecast has been wrong three quarters running, the diagnostic is the place to start.",
    commercialIntent: "high",
    scores: { novelty: 68, relevance: 98, proof: 84, fit: 92 },
    status: "scripted",
    rationale:
      "Highest commercial-intent theme in the workspace. Directly addresses the objection that most often prevents recognition of the real problem.",
  },
  {
    title: "The hidden cost of hiring an SDR too early",
    concept:
      "Part one of the running three-part series. The hiring decision, the assumption underneath it, and what it costs when the assumption is wrong.",
    pillar: "Hiring and team structure",
    platform: "linkedin",
    format: "talking_head",
    angle: "Cost-of-delay framing, anchored to a real client correction.",
    hookConcept: "Hiring an SDR before you can explain why deals are lost is the most expensive mistake in early-stage B2B.",
    objective: "Urgency and authority",
    cta: "Comment 'system' and I will send you the qualification framework.",
    commercialIntent: "high",
    scores: { novelty: 71, relevance: 92, proof: 88, fit: 90 },
    status: "scripted",
    rationale: "Part of an active test. Hiring topics reach further than forecasting topics.",
  },
  {
    title: "Why every closed-lost reason in your CRM is wrong",
    concept:
      "Loss reasons default to 'price' and 'timing' because nobody is incentivised to record the real one. What to capture instead and who should capture it.",
    pillar: "Qualification mechanics",
    platform: "youtube_shorts",
    format: "short_form",
    angle: "Take a universally recognised annoyance and explain the mechanism behind it.",
    hookConcept: "Every closed-lost in your CRM says price or timing. Both are usually lies.",
    objective: "Education with high recognition",
    cta: "The booking link is in my profile.",
    commercialIntent: "high",
    scores: { novelty: 66, relevance: 94, proof: 78, fit: 88 },
    status: "scripted",
    rationale:
      "The outlier signal shows this exact topic produced four qualified conversations from unremarkable reach.",
  },
  {
    title: "Your sales stages describe your activity, not their commitment",
    concept:
      "Most pipeline stages are named after what the seller did. Stages should be named after what the buyer committed to. Rebuilding them changes the forecast immediately.",
    pillar: "Forecasting and pipeline",
    platform: "linkedin",
    format: "talking_head",
    angle: "One structural correction with an immediate, visible effect.",
    hookConcept: "Your pipeline stages are named after things you did. That is why the forecast is wrong.",
    objective: "Mechanism explanation",
    cta: "Comment 'system' and I will send you the qualification framework.",
    commercialIntent: "high",
    scores: { novelty: 78, relevance: 92, proof: 74, fit: 86 },
    status: "approved",
    rationale: "Core mechanism content. Explains the offer without pitching it.",
  },
  {
    title: "The founder should be last in the deal, not first",
    concept:
      "Founders get pulled into deals as a rescue mechanism. Designing them in at the end instead of the beginning changes what the team can do without them.",
    pillar: "Founder POV",
    platform: "linkedin",
    format: "talking_head",
    angle: "Contrarian sequencing claim with a practical rule.",
    hookConcept: "By the time I get involved it has usually already gone wrong. That was a design problem, not a people problem.",
    objective: "Authority",
    cta: "If your forecast has been wrong three quarters running, the diagnostic is the place to start.",
    commercialIntent: "medium",
    scores: { novelty: 82, relevance: 90, proof: 70, fit: 88 },
    status: "approved",
    rationale: "Built from verbatim customer language captured on diagnostic calls.",
  },
  {
    title: "\"We tried a consultant and got a slide deck\"",
    concept:
      "Takes the objection seriously, agrees with it, and explains what working on live deals actually looks like week by week.",
    pillar: "Objection handling",
    platform: "linkedin",
    format: "talking_head",
    angle: "Concede the objection fully before answering it.",
    hookConcept: "Someone told me last month they had hired a sales consultant and got a slide deck. They were right to be annoyed.",
    objective: "Objection handling",
    cta: "The booking link is in my profile.",
    commercialIntent: "high",
    scores: { novelty: 64, relevance: 88, proof: 82, fit: 84 },
    status: "approved",
    rationale: "Directly addresses the most frequent objection recorded on diagnostic calls.",
  },
  {
    title: "The two SDRs I told a client to let go",
    concept:
      "A real engagement where the recommendation was to remove headcount rather than add process. What the closed-lost data showed and what happened the following year.",
    pillar: "Case studies and proof",
    platform: "linkedin",
    format: "talking_head",
    angle: "Counterintuitive recommendation backed by a documented outcome.",
    hookConcept: "I once told a client to let go of two people they had just hired.",
    objective: "Proof",
    cta: "Comment 'system' and I will send you the qualification framework.",
    commercialIntent: "high",
    scores: { novelty: 86, relevance: 88, proof: 94, fit: 90 },
    status: "approved",
    rationale: "Strongest available proof item, anonymised in line with compliance notes.",
  },
  {
    title: "A forecast that is wrong in a predictable direction is useful",
    concept:
      "Accuracy is not the goal; predictability is. A consistently 20% optimistic forecast can be corrected. A randomly wrong one cannot.",
    pillar: "Forecasting and pipeline",
    platform: "youtube_shorts",
    format: "short_form",
    angle: "Reframe what 'good forecast' means.",
    hookConcept: "A forecast that is wrong the same way every quarter is more useful than one that is nearly right.",
    objective: "Reframe",
    cta: "The booking link is in my profile.",
    commercialIntent: "medium",
    scores: { novelty: 88, relevance: 84, proof: 66, fit: 82 },
    status: "shortlisted",
    rationale: "A stated founder belief that has not yet been published.",
  },
  {
    title: "When should you actually hire your first AE?",
    concept:
      "The most frequently asked inbound question, answered as a readiness test rather than a revenue threshold.",
    pillar: "Hiring and team structure",
    platform: "linkedin",
    format: "talking_head",
    angle: "Answer the literal question, then correct the question itself.",
    hookConcept: "Everyone asks when to hire their first AE. It is the wrong question, and the right one takes five minutes to answer.",
    objective: "Lead generation",
    cta: "Comment 'system' and I will send you the qualification framework.",
    commercialIntent: "high",
    scores: { novelty: 62, relevance: 94, proof: 72, fit: 90 },
    status: "shortlisted",
    rationale: "The highest-volume recorded inbound question in the research set.",
  },
  {
    title: "The deal I lost at 90%",
    concept:
      "A deal forecast at 90% that was lost because nobody had ever spoken to the person who signs. The specific failure of single-threaded deals.",
    pillar: "Founder POV",
    platform: "linkedin",
    format: "talking_head",
    angle: "First-person failure with a mechanism attached.",
    hookConcept: "I lost a deal I had forecast at 90%. I had never spoken to the person who signs.",
    objective: "Authority",
    cta: "If your forecast has been wrong three quarters running, the diagnostic is the place to start.",
    commercialIntent: "medium",
    scores: { novelty: 76, relevance: 90, proof: 88, fit: 92 },
    status: "shortlisted",
    rationale:
      "Matches the highest-performing competitor format observed and the validated first-person learning.",
  },
  {
    title: "Pipeline hygiene is not a discipline problem",
    concept:
      "If the CRM only stays accurate when people are nagged, the CRM is designed wrong. What to change so accuracy is a by-product.",
    pillar: "Forecasting and pipeline",
    platform: "linkedin",
    format: "text_post",
    angle: "Move blame from people to design.",
    hookConcept: "If your CRM needs discipline to stay accurate, it is designed wrong.",
    objective: "Education",
    cta: "Comment 'system' and I will send you the qualification framework.",
    commercialIntent: "medium",
    scores: { novelty: 80, relevance: 82, proof: 64, fit: 78 },
    status: "shortlisted",
    rationale: "A stated founder belief, not yet published.",
  },
  {
    title: "Discovery calls that end in a booked demo are usually bad discovery calls",
    concept:
      "The demo is a reward for qualification, not a substitute for it. What good discovery actually ends with.",
    pillar: "Qualification mechanics",
    platform: "youtube_shorts",
    format: "short_form",
    angle: "Contrarian claim about a universally practised habit.",
    hookConcept: "If your discovery calls end with a demo booked, they are probably bad discovery calls.",
    objective: "Reframe",
    cta: "The booking link is in my profile.",
    commercialIntent: "medium",
    scores: { novelty: 84, relevance: 86, proof: 62, fit: 84 },
    status: "backlog",
    rationale: "Founder opinion with a clear contrarian hook.",
  },
  {
    title: "Three quarters of wrong forecasts is not bad luck",
    concept:
      "Pattern recognition: one miss is variance, three is structure. What to look at after the third.",
    pillar: "Forecasting and pipeline",
    platform: "linkedin",
    format: "talking_head",
    angle: "Threshold framing that matches a documented buying trigger.",
    hookConcept: "One missed forecast is variance. Three in a row is a structure problem.",
    objective: "Urgency",
    cta: "If your forecast has been wrong three quarters running, the diagnostic is the place to start.",
    commercialIntent: "high",
    scores: { novelty: 70, relevance: 96, proof: 70, fit: 86 },
    status: "backlog",
    rationale: "Maps directly to the strongest recorded buying trigger.",
  },
  {
    title: "What happens when your fractional CRO leaves",
    concept:
      "Positioning against buying a person rather than a system, without naming the competitor.",
    pillar: "Objection handling",
    platform: "linkedin",
    format: "talking_head",
    angle: "Take the competing option seriously, then follow it to its conclusion.",
    hookConcept: "Hiring a fractional CRO works. Right up until they leave.",
    objective: "Competitive positioning",
    cta: "The booking link is in my profile.",
    commercialIntent: "high",
    scores: { novelty: 78, relevance: 90, proof: 68, fit: 84 },
    status: "backlog",
    rationale: "Direct counter to the highest-threat competitor's core argument.",
  },
  {
    title: "The twelve-week handover nobody offers",
    concept:
      "Why the engagement has an end date, and what it says about consultancies that do not.",
    pillar: "Objection handling",
    platform: "linkedin",
    format: "text_post",
    angle: "Turn a constraint of the offer into the argument for it.",
    hookConcept: "Our engagement ends after twelve weeks. That is the point.",
    objective: "Offer clarity",
    cta: "The booking link is in my profile.",
    commercialIntent: "high",
    scores: { novelty: 74, relevance: 84, proof: 72, fit: 76 },
    status: "backlog",
    rationale: "Differentiator identified in competitor offer analysis.",
  },
  {
    title: "How to run a closed-lost review that produces something useful",
    concept: "The actual mechanics: who asks, when, what questions, and what to do with the answers.",
    pillar: "Qualification mechanics",
    platform: "youtube",
    format: "long_form",
    angle: "Full mechanism walkthrough for the highest-intent topic.",
    hookConcept: "Most closed-lost reviews produce nothing. Here is the version that works.",
    objective: "Education and lead generation",
    cta: "Comment 'system' and I will send you the qualification framework.",
    commercialIntent: "high",
    scores: { novelty: 66, relevance: 92, proof: 76, fit: 74 },
    status: "backlog",
    rationale:
      "Long-form test of the topic that produced the highest inquiry rate in short form.",
  },
  {
    title: "Your best AE leaving should not collapse the forecast",
    concept: "The dependency test: what breaks if one person goes.",
    pillar: "Hiring and team structure",
    platform: "linkedin",
    format: "talking_head",
    angle: "A diagnostic the reader can run on themselves in one minute.",
    hookConcept: "If your best AE left tomorrow, would the forecast survive? That is your answer.",
    objective: "Self-diagnosis",
    cta: "Comment 'system' and I will send you the qualification framework.",
    commercialIntent: "medium",
    scores: { novelty: 72, relevance: 88, proof: 62, fit: 86 },
    status: "backlog",
    rationale: "Founder belief expressed as a test the audience can apply immediately.",
  },
  {
    title: "The correction: what happened after we removed the SDRs",
    concept: "Part three of the running series. The outcome the following year.",
    pillar: "Case studies and proof",
    platform: "linkedin",
    format: "talking_head",
    angle: "Close the series with the documented result.",
    hookConcept: "Twelve months after we removed two SDRs, the same two AEs grew the number.",
    objective: "Proof",
    cta: "If your forecast has been wrong three quarters running, the diagnostic is the place to start.",
    commercialIntent: "high",
    scores: { novelty: 68, relevance: 90, proof: 92, fit: 88 },
    status: "backlog",
    rationale: "Completes the active three-part series test.",
  },
  {
    title: "Commission plans with more than two variables",
    concept: "Compensation complexity as a tax on attention. Why simpler plans forecast better.",
    pillar: "Hiring and team structure",
    platform: "linkedin",
    format: "text_post",
    angle: "A strong opinion on a topic founders quietly agonise over.",
    hookConcept: "If your commission plan has more than two variables, your reps are optimising for the spreadsheet.",
    objective: "Authority",
    cta: "The booking link is in my profile.",
    commercialIntent: "low",
    scores: { novelty: 80, relevance: 72, proof: 56, fit: 76 },
    status: "backlog",
    rationale: "Stated founder opinion. Lower commercial intent but strong voice fit.",
  },
  {
    title: "The eighteen months of reports that said everything was fine",
    concept:
      "The company that died while the pipeline reports looked healthy. What the reports were measuring instead.",
    pillar: "Founder POV",
    platform: "linkedin",
    format: "talking_head",
    angle: "The most serious story in the set, told without drama.",
    hookConcept: "The first company I worked at that died had eighteen months of reports saying everything was fine.",
    objective: "Authority",
    cta: "If your forecast has been wrong three quarters running, the diagnostic is the place to start.",
    commercialIntent: "medium",
    scores: { novelty: 88, relevance: 84, proof: 86, fit: 90 },
    status: "backlog",
    rationale: "Highest-novelty founder story available and directly on-topic.",
  },
  {
    title: "\"Our sales motion is unusual\"",
    concept: "The objection that a generic framework will not fit, and why it is usually half right.",
    pillar: "Objection handling",
    platform: "linkedin",
    format: "talking_head",
    angle: "Agree with the half that is true.",
    hookConcept: "Founders tell me their sales motion is unusual. They are half right, and the half they are wrong about is the expensive one.",
    objective: "Objection handling",
    cta: "The booking link is in my profile.",
    commercialIntent: "high",
    scores: { novelty: 70, relevance: 86, proof: 64, fit: 84 },
    status: "backlog",
    rationale: "Recorded objection from diagnostic calls.",
  },
  {
    title: "What 'qualified' means when nobody has defined it",
    concept: "The cost of an undefined term, and the shortest useful definition to start with.",
    pillar: "Qualification mechanics",
    platform: "youtube_shorts",
    format: "short_form",
    angle: "One definition, delivered plainly.",
    hookConcept: "Ask three people on your team what qualified means. You will get three answers.",
    objective: "Education",
    cta: "Comment 'system' and I will send you the qualification framework.",
    commercialIntent: "medium",
    scores: { novelty: 64, relevance: 90, proof: 60, fit: 84 },
    status: "backlog",
    rationale: "Recorded customer pain, phrased as a test.",
  },
  {
    title: "How long should a sales cycle be?",
    concept: "The wrong question. Variance matters more than length, and variance is fixable.",
    pillar: "Forecasting and pipeline",
    platform: "linkedin",
    format: "talking_head",
    angle: "Redirect a common question to the more useful metric.",
    hookConcept: "Nobody should care how long your sales cycle is. They should care how much it varies.",
    objective: "Reframe",
    cta: "Comment 'system' and I will send you the qualification framework.",
    commercialIntent: "medium",
    scores: { novelty: 76, relevance: 82, proof: 58, fit: 82 },
    status: "backlog",
    rationale: "Frequently asked inbound question.",
  },
  {
    title: "The board asked for our forecast methodology",
    concept:
      "Rising investor scrutiny of methodology rather than the number, and what to have ready.",
    pillar: "Forecasting and pipeline",
    platform: "linkedin",
    format: "text_post",
    angle: "Timely market observation with a practical preparation list.",
    hookConcept: "Investors have started asking how the forecast is built, not just what it says.",
    objective: "Timeliness",
    cta: "The booking link is in my profile.",
    commercialIntent: "high",
    scores: { novelty: 82, relevance: 86, proof: 54, fit: 74 },
    status: "backlog",
    rationale: "Built from a recorded market trend.",
  },
  {
    title: "Single-threaded deals are the most expensive habit in B2B",
    concept: "Why one champion is a liability and how to widen a deal without slowing it.",
    pillar: "Qualification mechanics",
    platform: "linkedin",
    format: "talking_head",
    angle: "Name the habit, quantify the exposure, give the fix.",
    hookConcept: "One champion is not a relationship. It is a single point of failure.",
    objective: "Education",
    cta: "Comment 'system' and I will send you the qualification framework.",
    commercialIntent: "medium",
    scores: { novelty: 62, relevance: 84, proof: 70, fit: 82 },
    status: "backlog",
    rationale: "Connects to the 90% deal loss story.",
  },
  {
    title: "The first thing I look at in a call recording",
    concept: "A specific, repeatable diagnostic the audience can run on their own recordings today.",
    pillar: "Qualification mechanics",
    platform: "youtube_shorts",
    format: "short_form",
    angle: "Give away one genuinely useful step of the method.",
    hookConcept: "When I open a client's call recordings, I skip to the same moment every time.",
    objective: "Method demonstration",
    cta: "The booking link is in my profile.",
    commercialIntent: "medium",
    scores: { novelty: 86, relevance: 88, proof: 72, fit: 88 },
    status: "backlog",
    rationale: "Demonstrates competence rather than describing it.",
  },
  {
    title: "Sales enablement content is usually a positioning problem",
    concept:
      "Teams build enablement material to compensate for a positioning decision nobody wants to make.",
    pillar: "Founder POV",
    platform: "linkedin",
    format: "text_post",
    angle: "Strong opinion connecting two functions founders treat separately.",
    hookConcept: "Most sales enablement content exists because nobody wanted to make a positioning decision.",
    objective: "Authority",
    cta: "Comment 'system' and I will send you the qualification framework.",
    commercialIntent: "low",
    scores: { novelty: 84, relevance: 70, proof: 48, fit: 78 },
    status: "backlog",
    rationale: "Stated founder opinion. Lower relevance to the immediate offer.",
  },
  {
    title: "What we do in weeks one to three",
    concept: "Transparent walkthrough of the audit phase, in enough detail to be useful alone.",
    pillar: "Case studies and proof",
    platform: "youtube",
    format: "long_form",
    angle: "Show the mechanism in full rather than teasing it.",
    hookConcept: "Here is exactly what happens in the first three weeks, including the part clients find uncomfortable.",
    objective: "Offer clarity",
    cta: "The booking link is in my profile.",
    commercialIntent: "high",
    scores: { novelty: 68, relevance: 88, proof: 80, fit: 72 },
    status: "backlog",
    rationale: "Makes the offer legible without pitching.",
  },
  {
    title: "Founders returning from holiday to a stalled pipeline",
    concept:
      "A recognisable pattern that reveals dependency. What it says about the system underneath.",
    pillar: "Founder POV",
    platform: "linkedin",
    format: "talking_head",
    angle: "A specific, common moment used as a diagnostic.",
    hookConcept: "If two weeks away stalls your pipeline, the problem was there before you left.",
    objective: "Self-diagnosis",
    cta: "If your forecast has been wrong three quarters running, the diagnostic is the place to start.",
    commercialIntent: "medium",
    scores: { novelty: 78, relevance: 86, proof: 62, fit: 86 },
    status: "backlog",
    rationale: "Recorded buying trigger.",
  },
  {
    title: "Ten sales metrics you should stop tracking",
    concept: "A list of vanity metrics and what to replace each with.",
    pillar: "Forecasting and pipeline",
    platform: "linkedin",
    format: "text_post",
    angle: "List format.",
    hookConcept: "Ten sales metrics worth deleting from your dashboard.",
    objective: "Reach",
    cta: "The booking link is in my profile.",
    commercialIntent: "low",
    scores: { novelty: 42, relevance: 64, proof: 40, fit: 52 },
    status: "rejected",
    rationale:
      "Rejected: list format under-performed badly and conflicts with the validated first-person learning.",
  },
  {
    title: "Sales trends to watch next year",
    concept: "Forward-looking commentary on where B2B sales is heading.",
    pillar: "Market commentary",
    platform: "linkedin",
    format: "text_post",
    angle: "Prediction piece.",
    hookConcept: "Five things that will change in B2B sales next year.",
    objective: "Reach",
    cta: "The booking link is in my profile.",
    commercialIntent: "low",
    scores: { novelty: 38, relevance: 48, proof: 24, fit: 46 },
    status: "rejected",
    rationale:
      "Rejected: no proof available, no first-person anchor, and predictions cannot be substantiated.",
  },
];
